#!/usr/bin/env bash
# Regenerate generated.md from the three statistics scripts.
# Run from anywhere inside the checkout; takes a few seconds.
#   formal/docs/stats/collect.sh [BASE]
# BASE is the commit the branch starts from (default a9d72b0ca), used for
# the C++ diff.
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$(git -C "$here" rev-parse --show-toplevel)"
base="${1:-a9d72b0ca}"
{
    echo "# Generated verification statistics"
    echo
    echo "Generated by \`formal/docs/stats/collect.sh\` at commit"
    echo "\`$(git rev-parse --short HEAD)\`$(git diff --quiet HEAD -- formal src || echo ' (with uncommitted changes)'). Do not edit by hand."
    echo
    echo "# Isabelle theories (theory_stats.py)"
    echo
    python3 "$here/theory_stats.py" formal/OfferExchange | sed 's/^## /### /'
    echo
    echo "# C++ covered by the code-level model (cxx_coverage.py)"
    echo
    python3 "$here/cxx_coverage.py" src "$here/coverage.tsv"
    echo
    echo "# Tests and build (test_stats.py)"
    echo
    python3 "$here/test_stats.py" "$base" | sed 's/^## /### /'
} > "$here/generated.md"
echo "wrote $here/generated.md"
