#!/usr/bin/env bash
# Regenerate generated.md from the three statistics scripts.
# Run from anywhere inside the checkout; takes a few seconds.
#   formal/docs/stats/collect.sh [BASE]
# BASE is the commit the branch starts from (default a9d72b0ca), used for
# the C++ diff.
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$(git -C "$here" rev-parse --show-toplevel)"
base="${1:-a9d72b0ca}"
# The figures depend on these inputs (and on the scripts and coverage.tsv,
# whose changes show up in the figures themselves).  Stamp the last commit
# that touched them, not HEAD, so that committing generated.md does not
# make it stale.
inputs=(formal/OfferExchange formal/differential src)
commit="$(git log -1 --format=%h -- "${inputs[@]}")"
dirty=""
if [ -n "$(git status --porcelain -- "${inputs[@]}")" ]; then
    dirty=" (with uncommitted changes)"
fi
out="$(mktemp "$here/generated.md.XXXXXX")"
trap 'rm -f "$out"' EXIT
{
    echo "# Generated verification statistics"
    echo
    echo "Generated by \`formal/docs/stats/collect.sh\` from the theories, the C++"
    echo "and the differential harness as of commit \`$commit\`$dirty. Do not edit"
    echo "by hand."
    echo
    echo "# Isabelle theories (theory_stats.py)"
    echo
    python3 "$here/theory_stats.py" formal/OfferExchange | sed 's/^## /### /'
    echo
    echo "# C++ covered by the code-level model (cxx_coverage.py)"
    echo
    python3 "$here/cxx_coverage.py" src "$here/coverage.tsv"
    echo
    echo "# Tests and build (test_stats.py)"
    echo
    python3 "$here/test_stats.py" "$base" | sed 's/^## /### /'
} > "$out"
chmod 644 "$out"
mv "$out" "$here/generated.md"
echo "wrote $here/generated.md"
