set-option -g default-shell /bin/bash

set -q -g status-utf8 on                  # expect UTF-8 (tmux < 2.2)
set -q -g utf8 on

# Set focus-events on (important for Neovim autoread)
set -g focus-events on

# tmux-256color instead of screen-256color enables italics
set-option -g default-terminal "tmux-256color"
# Tc enables true color
set -sa terminal-overrides ",*256col*:colors=256:Tc"

set -g history-limit 100000

set -s escape-time 10                     # faster command sequences
set -sg repeat-time 300                   # increase repeat timeout

# Set parent terminal title to reflect current window in tmux session
set -g set-titles on
set -g set-titles-string "#{?env:PROJECT_NAME,#{env:PROJECT_NAME},#T}"

# Start index of window/pane with 1, because we're humans, not computers
set -g base-index 1
setw -g pane-base-index 1

# resize a window based on the smallest client actually viewing it, not on the
# smallest one attached to the entire session:
setw -g aggressive-resize on

# pane navigation
bind -r h select-pane -L  # move left
bind -r j select-pane -D  # move down
bind -r k select-pane -U  # move up
bind -r l select-pane -R  # move right

# window navigation
unbind n
unbind p
bind -r C-h previous-window # select previous window
bind -r C-l next-window     # select next window
bind Tab last-window        # move to last active window

# -- copy mode -----------------------------------------------------------------

# Use vim keybindings in copy mode
set -g mode-keys vi

bind Enter copy-mode # enter copy mode

set -g set-clipboard on
set -g allow-passthrough on
set -as terminal-features ',*:clipboard'
set -ga terminal-overrides ',*:Ms=\E]52;c;%p2%s\a'

# copy like in vim
bind -T copy-mode-vi v   send -X begin-selection
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi Escape send -X cancel
bind -T copy-mode-vi H send -X start-of-line
bind -T copy-mode-vi L send -X end-of-line
bind -T copy-mode-vi y     send -X copy-pipe-and-cancel "OSC52_TTY=#{pane_tty} osc52-tmux"
bind -T copy-mode-vi Enter send -X copy-pipe-and-cancel "OSC52_TTY=#{pane_tty} osc52-tmux"

# -- buffers -------------------------------------------------------------------
bind b list-buffers  # list paste buffers
bind p paste-buffer  # paste from the top paste buffer
bind P choose-buffer # choose which buffer to paste from

# reload configuration
bind r source-file ~/.tmux.conf \; display '~/.tmux.conf sourced'
